# Generated by Django 3.2.13 on 2022-06-14 08:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0004_auto_20220613_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPageEndResult',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('galleryitems', wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([])), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(max_height=768, max_width=1024))]))])),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='youtube_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
