# Generated by Django 3.2.13 on 2022-06-14 09:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0005_auto_20220614_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypageendresult',
            name='galleryitems',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(blank=True)), ('buttons', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('label', wagtail.core.blocks.CharBlock())])), ('link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock()), ('label', wagtail.core.blocks.CharBlock())]))]))])), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(max_height=768, max_width=1024))]))]),
        ),
        migrations.CreateModel(
            name='NewPageEndResult',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('gallery', wagtail.core.blocks.StructBlock([]))])),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', wagtail.core.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
